"""initial_schema

Revision ID: 19baec5a2416
Revises: 
Create Date: 2026-04-13 01:51:10.605216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '19baec5a2416'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_masters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('charge_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('exclusion_group', sa.String(length=80), nullable=True),
    sa.Column('max_per_group', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessory_masters_code'), 'accessory_masters', ['code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_mobile'), 'customers', ['mobile'], unique=False)
    op.create_table('vehicle_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('variant_code', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('vehicle_group', sa.String(length=30), nullable=False),
    sa.Column('ex_showroom', sa.Float(), nullable=False),
    sa.Column('rto', sa.Float(), nullable=False),
    sa.Column('insurance', sa.Float(), nullable=False),
    sa.Column('standard_charges', sa.Float(), nullable=False),
    sa.Column('pdi', sa.Float(), nullable=False),
    sa.Column('extended_warranty', sa.Float(), nullable=False),
    sa.Column('rsa', sa.Float(), nullable=False),
    sa.Column('optional_accessories', sa.Float(), nullable=False),
    sa.Column('helmet', sa.Float(), nullable=False),
    sa.Column('ceramic', sa.Float(), nullable=False),
    sa.Column('tcs', sa.Float(), nullable=False),
    sa.Column('down_payment', sa.Float(), nullable=False),
    sa.Column('emi_24', sa.Float(), nullable=False),
    sa.Column('emi_36', sa.Float(), nullable=False),
    sa.Column('emi_48', sa.Float(), nullable=False),
    sa.Column('available_colors', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_variants_variant_code'), 'vehicle_variants', ['variant_code'], unique=True)
    op.create_table('accessory_compatibility',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('accessory_id', sa.String(length=36), nullable=False),
    sa.Column('variant_code', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessory_masters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessory_compatibility_accessory_id'), 'accessory_compatibility', ['accessory_id'], unique=False)
    op.create_index(op.f('ix_accessory_compatibility_variant_code'), 'accessory_compatibility', ['variant_code'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=False),
    sa.Column('vehicle_type', sa.String(length=60), nullable=False),
    sa.Column('model_code', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.Column('purchase_mode', sa.String(length=30), nullable=False),
    sa.Column('financer', sa.String(length=120), nullable=True),
    sa.Column('exchange', sa.Boolean(), nullable=False),
    sa.Column('old_vehicle', sa.String(length=120), nullable=True),
    sa.Column('kms', sa.Integer(), nullable=True),
    sa.Column('owner_count', sa.String(length=30), nullable=True),
    sa.Column('sales_executive', sa.String(length=120), nullable=False),
    sa.Column('buying_when', sa.String(length=120), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_status'), 'inquiries', ['status'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inquiry_id', sa.String(length=36), nullable=False),
    sa.Column('quote_number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('preview_data', sa.JSON(), nullable=False),
    sa.Column('pdf_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_inquiry_id'), 'quotes', ['inquiry_id'], unique=False)
    op.create_index(op.f('ix_quotes_quote_number'), 'quotes', ['quote_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_quote_number'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_inquiry_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_inquiries_status'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_accessory_compatibility_variant_code'), table_name='accessory_compatibility')
    op.drop_index(op.f('ix_accessory_compatibility_accessory_id'), table_name='accessory_compatibility')
    op.drop_table('accessory_compatibility')
    op.drop_index(op.f('ix_vehicle_variants_variant_code'), table_name='vehicle_variants')
    op.drop_table('vehicle_variants')
    op.drop_index(op.f('ix_customers_mobile'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_accessory_masters_code'), table_name='accessory_masters')
    op.drop_table('accessory_masters')
    # ### end Alembic commands ###
